FROM golang:1.13.4

RUN apt-get update \
    && apt-get install -y npm \
    && apt-get install -y ruby-dev build-essential
    && npm install -g yarn \
    && gem install fpm

CMD ["yarn", "start"]

