#!/bin/bash

#for mac

version=1.0

if [ $# -gt 1 ]; then
  echo "Usage: $0 [service]"
  echo "  service: prom/grafana/vehicle/client/server, server means prom + grafana + vehicle. Default is blank, meaning start them all."
  exit 0
fi

if [ $# = 0 ]; then
  grafana=true
  prom=true
  vehicle=true
  client=true
fi

arg=ops

if [ "$1" = "server" ]; then
  grafana=true
  prom=true
  vehicle=true
fi

if [ "$1" = "grafana" ]; then
  grafana=true
fi

if [ "$1" = "prom" ]; then
  prom=true
fi

if [ "$1" = "vehicle" ]; then
  vehicle=true
fi

if [ "$1" = "client" ]; then
  client=true
fi

if [ $grafana ]; then
  echo -e
  echo "#### starting grafana ####"
  image=frankhang/grafana:$version
  docker stop grafana
  docker rm grafana
  docker run --name grafana -d -p 3300:3300 -v ~/grafanadata:/var/lib/grafana $image
fi

if [ $prom ]; then
  echo -e
  echo "#### starting prom ####"
  image=frankhang/prom-$arg:$version
  docker stop prom
  docker rm prom
  docker run --name prom -d -p 8090:8090 -v ~/promdata:/etc/prometheus/data $image
# docker run --name prom -d -p 8090:8090 $image

fi

if [ $vehicle ]; then
  echo -e
  echo "#### starting vehicle ####"
  image=frankhang/iot-vehicle:$version
  docker stop vehicle
  docker rm vehicle
  docker run --name vehicle -d -p 10002:10002 $image -L=debug
fi

if [ $client ]; then
  echo -e
  echo "#### starting client  ####"
  image=frankhang/client:$version
  docker stop client1
  docker rm client1
  docker stop client2
  docker rm client2
  docker run --name client1 -d $image -url=host.docker.internal:8125
  docker run --name client2 -d $image -url=host.docker.internal:8125
fi
